% -------------------------------------------------------------------
%  Generated by MATLAB on 13-Dec-2016 20:06:51
%  MATLAB version: 9.0.0.341360 (R2016a)
% -------------------------------------------------------------------
saveVarsMat = load('Mihnea_Niculae_SP_t2.mat');

D = 20;

N = 50;

P = 40;

c0 = 0;

cn = 0;

duty = 50;

n = 49;

t = saveVarsMat.t; % <1x5001 double> too many elements

ttle = 'Spectrul Amplitudinilor 50';

wo = 0.15707963267948966;

x2 = saveVarsMat.x2; % <1x5001 double> too many elements

yce = saveVarsMat.yce; % <1x5001 double> too many elements

clear saveVarsMat;
